### ISSUE TITLE
add a first run routine

### ISSUE THREAD

**Issue by theunkn0wn1** [beepbeat/JAFRDB#14]
It is not exactly user friendly to require them to download a template config file and expect them to correctly fill it out the first time.

issue:
---------
this program appears to depend on a config file yet does not generate it upon first run.
This leads to other bugs and errors that are confusing to non-tech users.

possible solution:
---------
add a first run routine that, in the event a config file is not found / settings are invalid prompts the user via a messagebox or other GUI means to enter the config options. This prompt will then write these values, along with defaults to config keys the user does not configure, to a config file in the correct directory.

**Comment by Holladiewal** [comment]
Default value writing is in place
