### ISSUE TITLE
closing the programs main window does not close the program

### ISSUE THREAD

**Issue by theunkn0wn1** [beepbeat/JAFRDB#16]
When the main window for the program is closed via clicking the red x (on windows) your program does not exit and continues running in the background.
The only clean way to exit the application is to hit x while focused on the main window

Issue:
---------

The program ignores my attempt to gracefully terminate it via common-sense and intented methods. This forces me to taskkill.
![image](https://user-images.githubusercontent.com/3110986/32921475-9cc5ea8a-cae2-11e7-8f31-e5ef180b475f.png)

**Comment by Holladiewal** [comment]
Closing the main window via common-sense method is disabled
